//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvccurdStoredProcedureWithEntityFrameWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class databaseEntities : DbContext
    {
        public databaseEntities()
            : base("name=databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
    
        public virtual int sp_delete_branch(Nullable<int> bid, string bname)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var bnameParameter = bname != null ?
                new ObjectParameter("bname", bname) :
                new ObjectParameter("bname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_branch", bidParameter, bnameParameter);
        }
    
        public virtual ObjectResult<sp_find_branch_Result> sp_find_branch(Nullable<int> bid)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_find_branch_Result>("sp_find_branch", bidParameter);
        }
    
        public virtual int sp_insert_branch(Nullable<int> bid, string bname)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var bnameParameter = bname != null ?
                new ObjectParameter("bname", bname) :
                new ObjectParameter("bname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_branch", bidParameter, bnameParameter);
        }
    
        public virtual ObjectResult<sp_select_branch_Result> sp_select_branch()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_select_branch_Result>("sp_select_branch");
        }
    
        public virtual int sp_update_branch(Nullable<int> bid, string bname)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var bnameParameter = bname != null ?
                new ObjectParameter("bname", bname) :
                new ObjectParameter("bname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_branch", bidParameter, bnameParameter);
        }
    }
}
